name:  Open edX Tutor k8s create jwt
description: Github Action to configure a javascript web token (jwt) for use in Open edX applications
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namespace to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
      # retrieve the Open edX JWT token that we created with Terraform and
      # then stored in Kubernetes secrets
      - name: Fetch JWT token from k8s secrets
        id: get-secret
        shell: bash
        run: |-
          kubectl get secret jwt -n ${{ inputs.namespace }} -o json |  jq  '.data| map_values(@base64d)'  | jq -r 'keys[] as $k | "\(.[$k])"' > jwt_private_key

      - name: Generate JWT private key
        id: initialize-variable
        shell: bash
        run:  |-
          export TUTOR_JWT_RSA_PRIVATE_KEY=\'$(sed -E 's/$/\n/g' ./jwt_private_key)\'

      - name: tutor config
        id: save-config
        shell: bash
        run: tutor config save
